<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ALIPL0482.local" failures="1" tests="3" name="Test" time="24.715" errors="0" timestamp="27 Nov 2020 10:26:11 GMT">
  <testcase classname="com.qa.tests.LoginTests" name="invalidPassword" time="5.962">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.new] but found [Username and password do not match any user in this service.]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.new] but found [Username and password do not match any user in this service.]
at com.qa.tests.LoginTests.invalidPassword(LoginTests.java:108)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- invalidPassword -->
  <testcase classname="com.qa.tests.LoginTests" name="invalidusername" time="3.221"/>
  <testcase classname="com.qa.tests.LoginTests" name="successLogin" time="4.769"/>
</testsuite> <!-- Test -->
